import Breadcrumb from "@/src/components/common/breadcrumb";
import { poppins_500, poppins_600 } from "@/src/components/common/font";
import {
  Box,
  Button,
  Container,
  Divider,
  Grid,
  Link,
  Stack,
  TextField,
  Typography,
} from "@mui/material";
import Head from "next/head";
import React from "react";
import CallIcon from "@mui/icons-material/Call";
import MailOutlineIcon from "@mui/icons-material/MailOutline";
import LocationOnIcon from "@mui/icons-material/LocationOn";
import styles from "@/styles/Home.module.css";
import { theme } from "@/src/utils/theme";
import { styled } from "@mui/system";
import ContactDetail from "@/src/components/contact/contactDetail";
import GetInTouch from "@/src/components/contact/getInTouch";
const MyStyledBox = styled(Box)(({ theme }) => ({
  "& .MuiFilledInput-input": { paddingTop: "20px" },
  "& .MuiInputLabel-root": { color: "#151515", fontSize: "14px" },
  "& .MuiFilledInput-root": {
    borderRadius: "100px",
    backgroundColor: "#F3F4F9",
  },
  "& .MuiFilledInput-root:before": { borderBottom: "unset !important" },
}));
const Index = () => {
 
  return (
    <>
      <Head>
        <title>Agent Portal | Contact us</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box>
        <Breadcrumb page_name="Contact Us" />
        <Container>
          <Grid container py={8}>
            <Grid item md={6} sx={{padding:{md:"0px 70px"}}}>
        <ContactDetail/>
            </Grid>
            <Grid
              item
              md={6}              
              sx={{padding:{md:"0px 70px"},borderLeft:{md:"1px solid #EBEBEB"}}}
            >
             <GetInTouch/>
            </Grid>
          </Grid>
        </Container>
      </Box>
    </>
  );
};

export default Index;
