import React from "react";
import { Box, Container, Typography} from "@mui/material";
import Head from "next/head";
const index = () => {
  return (
    <>
      <Head>
        <title>Comming soon</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     <Box bgcolor={'#455acf4f'}>
     <Container sx={{textAlign:'center', padding:'200px 0px'}}>
       <Typography sx={{fontSize:'50px', fontWeight:'600', textTransform:'uppercase'}}>We’ll be back soon!</Typography>
       <Typography sx={{fontSize:'25px'}}>Sorry for the inconvenience but we&rsquo;re performing some maintenance at the moment.</Typography>

      </Container>
     </Box>
    </>
  );
};

export default index;
