import Breadcrumb from "@/src/components/common/breadcrumb";
import ScheduleVisit from "@/src/components/schedule_visit/scheduleVisit";
import { Box, Container, Divider, Grid, Typography } from "@mui/material";
import Head from "next/head";
import React from "react";
import ScheduleProperty from "@/src/components/schedule_visit/scheduleProperty";
const index = () => {

  return (
    <>
      <Head>
        <title>Schedule Visit</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Breadcrumb page_name="Schedule Visit" />
      <Box bgcolor={"#F3F4F9"}>
        <Container sx={{ py: 8 }}>
          <Grid container>
            <Grid item md={4} sm={12} xs={12} sx={{my:{sm:2,md:0,xs:2}}}>
             <ScheduleProperty/>
            </Grid>
            <Grid item md={8} sm={12} xs={12} sx={{pl:{md:3}}}>
              <ScheduleVisit />
            </Grid>
          </Grid>
        </Container>
      </Box>
    </>
  );
};

export default index;
