import Head from "next/head";
import { Box, Container, Grid, ThemeProvider, Typography } from "@mui/material";
import { theme } from "@/src/utils/theme";
import {
  poppins_400,
  poppins_500,
  poppins_600,
  roboto_400,
} from "@/src/components/common/font";
import PropListSidebar from "@/src/components/property/propListSidebar";
import PropertyCard from "@/src/components/common/propertyCard";
import Propimg1 from "@/public/assets/images/property/prop-list1.png";
import Propimg2 from "@/public/assets/images/property/prop-list2.png";
import Propimg3 from "@/public/assets/images/property/prop-list3.png";
import Breadcrumb from "@/src/components/common/breadcrumb";
import { userProfileDetail } from "@/src/utils/axios";
import { useEffect, useState } from "react";
const Myfavorite = () => {
  const [favoriteProperty, setFavoriteProperty] = useState()
  const getUserDetails=async()=>{
    let res=await userProfileDetail()

 
    setFavoriteProperty(res?.data)
   }
   useEffect(() => {
     getUserDetails()
     
   }, [])

  

  return (
    <>
      <Head>
        <title>My favorite Property</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Breadcrumb root_page="" root_page_path="" page_name="My Favorites" />
      <Box bgcolor={"#F3F4F9"}>
        <Container sx={{ py: 8 }}>
          <Grid container>
            
            <Grid item md={8} xs={12} pr={3}>
              <Box bgcolor={"#fff"} p={3}>
                <Typography
                  textAlign={"center"}
                 variant='poppins_600' component={'p'}
                       sx={{fontSize:{sm:'50px',xs:'30px'}}}
                  color={"space.main"}
                  letterSpacing={"1.44px"}
                >
                  My{" "}
                  <Typography
                   variant='poppins_600'
                         sx={{fontSize:{sm:'50px',xs:'30px'}}}
                    color={"gold.main"}
                    component="span"
                  >
                    Favorites
                  </Typography>
                </Typography>
                <Typography
                  textAlign={"center"}
                 variant='poppins_600' component={'p'}
                 sx={{fontSize:{sm:'20px',xs:'15px'}}}
                  color={"space.main"}
                  letterSpacing={"1.44px"}
                >
                  Properties You are interested in renting or buying.
                </Typography>
              </Box>

              <Grid container my={3}>               
                {favoriteProperty?.myFavoritePropertyData?.map((item, index) => (
                  <Grid
                    key={index}
                    item
                    sm={6}
                    xs={12}
                    mb={1}
                    sx={{
                      paddingRight:{md: index % 2 === 0 ? 1 : 0},
                      paddingLeft:{md:index % 2 !== 0 ? 2 : 0},
                    }}
                  >
                    <PropertyCard
                    status={item.status}
                    property_id={item.property_id}
                    imgUrl={item.property_images_arr}
                    title={item.title}
                    area={item.sqFtarea}
                    bathroom={item.bathroomCount}
                    bedroom={item.bhkType}
                    max_price={item.max_price}
                    isCheckBoxTrue={true}
                    isCheckedTrue={false}
                    isAmenities={true}
                    routingUrl={'/property/'+item.title.replace(/\s+/g, '-')+'-'+item.property_id}
                    verified_flag={item.verified_flag}
                    />
                  </Grid>
                ))}
              </Grid>

              {favoriteProperty?.myFavoritePropertyData?.length === 0 && (
                <Typography
                  sx={{ fontSize: "40px", color: "#d9d9d9",textAlign:'center' }}
                  className={poppins_600.className}
                >
                  No Data Found
                </Typography>
              )}
            </Grid>
            <Grid item md={4} xs={12}>
              <PropListSidebar />
            </Grid>
          </Grid>
        </Container>
      </Box>
    </>
  );
};

export default Myfavorite;
