import Head from "next/head";
import {
  Container,
  Paper,
  ThemeProvider,
  Typography,
} from "@mui/material";


import PostProperty from "@/src/components/property/postProperty";
import Breadcrumb from "@/src/components/common/breadcrumb";


export default function Index() {

  return (
    <>
      <Head>
        <title>Agent Portal | Post-Property</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Breadcrumb root_page="" root_page_path="" page_name="Post Property" />
  
        <Container sx={{ py: 5, }}>
          <Paper sx={{p:{md:7,sm:2,xs:1}}}>
          <PostProperty />
          </Paper>
        </Container>
  
    </>
  );
}
